/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package github.osberg.acme

import github.osberg.acme.config.RetrofitClientConfig
import github.osberg.acme.service.EngagementClassifierService
import github.osberg.acme.service.ForecastConverterService
import github.osberg.acme.service.OpenWeatherService

val openWeatherService = OpenWeatherService( RetrofitClientConfig().openWeatherApi)
val engagementClassifierService = EngagementClassifierService(ForecastConverterService(), openWeatherService)

fun main(args: Array<String>) {
    engagementClassifierService.printClassifiersForCity("Minneapolis")
}
