/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package github.osberg.acme

import github.osberg.acme.service.OpenWeatherService

val openWeatherService = OpenWeatherService()

fun main(args: Array<String>) {
    println(openWeatherService.getFiveDayForecastFor("Minneapolis"))
}
